<?php
namespace Rexume\Lib\Formatters;
class FakeObject{
	public $noComments;
    /**
     *
     * @format={attribute}
     */
	public $hasAttribute;
    /**
     *
     * @format={attribute,collapsed}
     */
	public $collapsedAttribute;
}

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-12-21 at 05:29:40.
 */
class ReflectiveXMLSerializerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ReflectiveXMLSerializer
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ReflectiveXMLSerializer(new FakeObject());
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Config\DataObject::isAttribute
     * @todo   Implement testIsAttribute().
     */
    public function testIsAttribute() {
        $this->assertTrue($this->object->isAttribute('hasAttribute'));
        $this->assertTrue($this->object->isAttribute('collapsedAttribute'));
        $this->assertFalse($this->object->isAttribute('noComments'));
    }

    /**
     * @covers Rexume\Config\DataObject::isCollapsed
     * @todo   Implement testIsCollapsed().
     */
    public function testIsCollapsed() {
        $this->assertFalse($this->object->isCollapsed('hasAttribute'));
        $this->assertTrue($this->object->isCollapsed('collapsedAttribute'));
        $this->assertFalse($this->object->isCollapsed('noComments'));
    }
}
