<?php

namespace Rexume\Parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-13 at 06:48:37.
 */
class CommaDelimitedParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var CommaDelimitedParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new CommaDelimitedParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

}
