<?php

namespace Rexume\Parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-13 at 06:48:38.
 */
class DelimitedParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var DelimitedParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new DelimitedParser(array(), 'string');
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Parsers\DelimitedParser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
