<?php

namespace Rexume\Lib\Parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-18 at 02:24:53.
 */
class ProtocolParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var ProtocolParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new ProtocolParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Lib\Parsers\ProtocolParser::createBinding
     * @todo   Implement testCreateBinding().
     */
    public function testCreateBinding() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\ProtocolParser::createMapping
     * @todo   Implement testCreateMapping().
     */
    public function testCreateMapping() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\ProtocolParser::parseProtocols
     * @todo   Implement testParseProtocols().
     */
    public function testParseProtocols() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\ProtocolParser::parseProtocol
     * @todo   Implement testParseProtocol().
     */
    public function testParseProtocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
