<?php

namespace Rexume\Lib\Parsers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-18 at 02:24:53.
 */
class XMLSimpleParserTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var XMLSimpleParser
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new XMLSimpleParser;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Lib\Parsers\XMLSimpleParser::parse
     * @todo   Implement testParse().
     */
    public function testParse() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\XMLSimpleParser::getValue
     * @todo   Implement testGetValue().
     */
    public function testGetValue() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\XMLSimpleParser::getValues
     * @todo   Implement testGetValues().
     */
    public function testGetValues() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Lib\Parsers\XMLSimpleParser::getObject
     * @todo   Implement testGetObject().
     */
    public function testGetObject() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
