<?php

namespace Rexume\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-13 at 06:53:46.
 */
class ControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var Controller
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new Controller;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Controllers\Controller::__destruct
     * @todo   Implement test__destruct().
     */
    public function test__destruct() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Controllers\Controller::getView
     * @todo   Implement testGetView().
     */
    public function testGetView() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Controllers\Controller::getModel
     * @todo   Implement testGetModel().
     */
    public function testGetModel() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
