<?php

namespace Rexume\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-13 at 07:44:49.
 */
class NavigationControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var NavigationController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new NavigationController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Controllers\NavigationController::pageNotFound
     * @todo   Implement testPageNotFound().
     */
    public function testPageNotFound() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Controllers\NavigationController::accessDenied
     * @todo   Implement testAccessDenied().
     */
    public function testAccessDenied() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
