<?php

namespace Rexume\Controllers;

/**
 * Generated by PHPUnit_SkeletonGenerator 1.2.0 on 2012-10-13 at 07:39:57.
 */
class VerificationControllerTest extends \PHPUnit_Framework_TestCase {

    /**
     * @var VerificationController
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new VerificationController;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @covers Rexume\Controllers\VerificationController::display
     * @todo   Implement testDisplay().
     */
    public function testDisplay() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Controllers\VerificationController::getOAuthData
     * @todo   Implement testGetOAuthData().
     */
    public function testGetOAuthData() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

    /**
     * @covers Rexume\Controllers\VerificationController::protocol
     * @todo   Implement testProtocol().
     */
    public function testProtocol() {
        // Remove the following lines when you implement this test.
        $this->markTestIncomplete(
                'This test has not been implemented yet.'
        );
    }

}
